# Generated by Django 4.2.25 on 2025-10-14 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP_Protector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Set an RSVP Password.', max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='personID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique Person ID for this particular person.', primary_key=True, serialize=False),
        ),
    ]
