# Generated by Django 4.2.25 on 2025-10-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_person_email_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='associated_family',
            field=models.ForeignKey(help_text='Enter the family last name associated with this person.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='people', to='rsvp.family'),
        ),
    ]
