# Generated by Django 5.2.8 on 2026-03-09 03:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_remove_person_email_remove_person_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, null=True, region=None),
        ),
    ]
