# Generated by Django 4.2.25 on 2025-10-14 04:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('familyID', models.UUIDField(default=uuid.uuid4, help_text='Unique Family ID for this particular family.', primary_key=True, serialize=False)),
                ('family_name', models.CharField(help_text='Enter the family last name.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.UUIDField(default=uuid.uuid4, help_text='Unique Family ID for this particular family.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Enter the person's first name.", max_length=20)),
                ('last_name', models.CharField(help_text="Enter the person's last name.", max_length=20)),
                ('status', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', help_text='RSVP Status.', max_length=1)),
                ('associated_family', models.ForeignKey(help_text='Enter the family last name associated with this person.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='rsvp.family')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
